using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static System.Console;
using System.Collections.Specialized;

namespace Dictionary
{
    class Program
    {
        static void Main(string[] args)
        {

            NameValueCollection dict = new NameValueCollection();
            dict.Add("abaft", "(adverb) to the rear of, aft of, behind ");
            dict.Add("abasement", "(noun) the act of making someone seem less important or less deserving of respect");
            dict.Add("abash", "(verb) to embarrass someone or make them feel uncomfortable");
            dict.Add("abatement", "(noun) a reduction in the amount or degree of something");
            dict.Add("abattoir", "(noun) a place where animals are killed for their meat");
            dict.Add("abalone", "(noun) a small sea creature thaat can be eaten");
            dict.Add("abalone", " it live inside a shell that is the shape of an ear and is white and shiny inside");
            dict.Add("abandon", "(noun) a feeling or attitude of wild or complete freedom");
            dict.Add("abandon", "\n\t(verb) to leave and never return to");
            dict.Add("abase", "(verb) to lower in position, estimation, or the like; degrade");
            dict.Add("abbess", "(noun) the lady superior of a nunnery");
            dict.Add("abbey", "(noun) the group of buildings which collectively form the dwelling-place of a society of monks or nuns");
            dict.Add("abbot", "(noun) the superior of a community of monks");
            dict.Add("abduction", "(noun) a carrying away of a person against his will");
            dict.Add("abduction", " illegally");
            dict.Add("abed", "(adverb) in bed");
            dict.Add("abed", " on a bed");
            dict.Add("ability", "(noun) the power or skill to do something");
            dict.Add("able", "(adjective) having the power, skill, money, etc., that is needed to do something");
            dict.Add("able", " not prevented from doing something");
            dict.Add("able", " used to say that the quality or condition of something makes something possible");
            dict.Add("able", " having skill or talent");
            dict.Add("abnormal", "(adjective) not conformed to the ordinary rule or standard");
            dict.Add("about", "(adverb) almost or nearly");
            dict.Add("about", " used to indicate that a number, amount, time, etc., is not exact or certain");
            dict.Add("about", " very close to doing something");
            dict.Add("about", "\n\t(preposition) used to indicate the object of a thought, feeling, or action");
            dict.Add("about", " used to indicate the most important or basic part or purpose of something");
            dict.Add("above", "(adverb) in or to a higher place");
            dict.Add("above", " in or to a higher rank or number");
            dict.Add("above", "\n\t(preposition) in or to a higher place than (something)");
            dict.Add("above", " greater in number, quantity, or size than (something)");
            dict.Add("above", "\n\t(adjective) mentioned at an earlier point in the same document");
            dict.Add("abroad", "(adverb) in or to a foreign country");
            dict.Add("abroad", " going from one person to the next");
            dict.Add("absence", "(noun) a state or condition in which something expected, wanted, or looked for is not present or does not exist");
            dict.Add("absence", " a failure to be present at a usual or expected place");
            dict.Add("absence", " a period of time when someone is not present at a place, job, etc.");
            dict.Add("absent", "(adjective) not present at a usual or expected place");
            dict.Add("absent", "\n\t(verb) to go or stay away from something");
            dict.Add("absent-minded", "(adjective) lacking in attention to immediate surroundings or business");
            dict.Add("absorb", "(verb) to drink in or suck up, as a sponge absorbs water");
            dict.Add("absorption", "(noun) the act or process of absorbing");
            dict.Add("absurd", "(adjective) inconsistent with reason or common sense");
            dict.Add("abusive", "(adjective) employing harsh words or ill treatment");
            dict.Add("academic", "(adjective) of or pertaining to an academy, college, or university");
            dict.Add("academician", "(noun) a member of an academy of literature, art, or science");
            dict.Add("academy", "(noun) any institution where the higher branches of learning are taught");
            dict.Add("active", "(adjective) busy doing thing or doing something regulary");
            dict.Add("action", "(noun) the process of doing something in order to make something");
            dict.Add("action", " fightting or war");
            dict.Add("act", "(noun) pretending");
            dict.Add("act", " a law or a particular.");
            dict.Add("act", "\n\t (verb) do something or pretend to be a type of something.");
            dict.Add("accelerate", "(verb) to move faster");
            dict.Add("acknowledge", "(verb) to accept, admit, or recognize somethingm");
            dict.Add("acknowledge", " the truth or existence of something.");
            dict.Add("acquire", "(verb) to get or buy something");
            dict.Add("accept", "(verb) to take when offered");
            dict.Add("access", "(noun) a way of approach or entrance, passage");
            dict.Add("accessible", "(adjective) approachable");
            dict.Add("accession", "(noun) induction or elevation, as to dignity, office, or government");
            dict.Add("accessory", "(noun) a person or thing that aids the principal agent");
            dict.Add("accommodate", "(verb) to furnish something as a kindness or favor");
            dict.Add("accompany", "(verb) to go with, or be associated with, as a companion");
            dict.Add("account", "(noun) A record or statement of receipts and expenditures, or of business transactions");
            dict.Add("accuracy", "(noun) exactness");
            dict.Add("accurate", "(adjective) conforming exactly to truth or to a standard");
            dict.Add("accusation", "(noun) a charge of crime, misdemeanor, or error");
            dict.Add("accusatory", "(adjective) of, pertaining to, or involving an accusation");
            dict.Add("accuse", "(verb) to charge with wrong doing, misconduct, or error");
            dict.Add("ache", "(verb) to be in pain or distress");
            dict.Add("acid", "(noun) a sour substance");
            dict.Add("acknowledge", "(verb) to recognize; to admit the genuineness or validity of");
            dict.Add("acknowledgment", "(noun) recognition");
            dict.Add("acquire", "(verb) to get as one's own");
            dict.Add("acquit", "(verb) to free or clear, as from accusation");
            dict.Add("administrator", "(noun) one who manages affairs of any kind");
            dict.Add("advert", "(verb) to refer incidentally");
            dict.Add("advertiser", "(noun) one who advertises, especially in newspapers");
            dict.Add("affect", "(verb) to act upon");
            dict.Add("affectation", "(noun) a studied or ostentatious pretense or attempt");
            dict.Add("afternoon", "(noun) the period that starts at about twelve o'clock or after the meal in the middle of the day and ends at about six o'clock or when the sun goes down");
            dict.Add("album", "(noun) a book whose leaves are so made to form paper frames for holding photographs or the like");
            dict.Add("ambitious", "(adjective) eagerly desirous and aspiring");
            dict.Add("anatomy", "(noun) that branch of morphology which treats of the structure of organisms");
            dict.Add("apple", "(noun) the round fruit of a tree of the rose family, which typically has thin green or red skin and crisp flesh");
            dict.Add("aqueous", "(adjective) of, pertaining to, or containing water");
            dict.Add("arrange", "(verb) to put in definite or proper order");
            dict.Add("ascent", "(noun) a rising, soaring, or climbing");
            dict.Add("atheism", "(noun) the denial of the existence of God");
            dict.Add("audible", "(adjective) loud enough to be heard");
            dict.Add("avert", "(verb) to turn away or aside");
            dict.Add("awaken", "(verb) to arouse, as emotion, interest, or the like");
            dict.Add("aye", "(adverb) an expression of assent");
            dict.Add("azure", "(noun) the color of the sky");
            dict.Add("bacterium", "(noun) a microbe");
            dict.Add("banana", "(noun) a long curved fruit which grows in clusters and has soft pulpy flesh and yellow skin when ripe");
            dict.Add("bee", "(noun) an insect of a large group to which the honeybee belongs, including many solitary as well as social kinds");
            dict.Add("beck", "(verb) to give a signal to, by nod or gesture");
            dict.Add("biology", "(noun) the science of life or living organisms");
            dict.Add("blaze", "(verb) a vivid glowing flame");
            dict.Add("boy", "(noun) a male child or youth");
            dict.Add("brave", "(adjective) ready to face and endure danger or pain; showing courage");
            dict.Add("brave", "\n\t(verb) endure or face without showing fear");
            dict.Add("brother", "(noun) a man or boy with the same parents as another person");
            dict.Add("bullock", "(noun) an ox");
            dict.Add("burn", "(verb) to destroy, damage, or injure by heat or fire");
            dict.Add("burn", "\n\t(noun) an injury caused by exposure to heat or flame");
            dict.Add("cat", "(noun) a small animal that is related to lions and tigers and that is often kept by people as a pet");
            dict.Add("car", "(noun) a four-wheeled road vehicle that is powered by an engine and is able to carry a small number of people");
            dict.Add("cede", "(verb) to pass title to");
            dict.Add("charm", "(noun) the power or quality of delighting, attracting, or fascinating others");
            dict.Add("city", "(noun) a large town");
            dict.Add("clown", "(noun) a comic entertainer, especially one in a circus, wearing a traditional costume and exaggerated make-up");
            dict.Add("clown", "\n\t (verb) behave in a comical or playful way");
            dict.Add("code", "(noun) program instructions");
            dict.Add("code", "\n\t (verb) write code for (a computer program)");
            dict.Add("cracked", "(adjective) crazy, insane");
            dict.Add("cute", "(adjective) attractive in a pretty or endearing way");
            dict.Add("cycle", "(noun) a series of events that are regularly repeated in the same order");
            dict.Add("day", "(noun) a period of 24 hours beginning at midnight : one of the seven time periods that make up a week");
            dict.Add("death", "(noun) the state of being dead");
            dict.Add("die", "(verb) to stop living");
            dict.Add("dog", "(noun) a type of animal that is often kept as a pet or trained to work for people by guarding buildings, hunting, etc");
            dict.Add("door", "(noun) a part of an object that swings or slides open and shut");
            dict.Add("draw", "(verb) produce by making lines and marks on paper with a pencil, pen, etc");
            dict.Add("duck", "(noun) a pure white thin-shelled bivalve mollusc found off the Atlantic coasts of America");
            dict.Add("eat", "(verb) put food into the mouth and chew and swallow it");
            dict.Add("earth", "(noun) the planet on which we live; the world");
            dict.Add("economic", "(adjective) relating to economics or the economy");
            dict.Add("edit", "(verb) prepare written material for publication by correcting, condensing, or otherwise modifying it");
            dict.Add("effect", "(noun) a consequence");
            dict.Add("ego", "(noun) a person's sense of self-esteem or self-importance");
            dict.Add("egg", "(noun) the oval object with a hard shell that is produced by female birds, especially chickens, eaten as food");
            dict.Add("eight", "(noun) the number 8");
            dict.Add("elephant", "(noun) a very large gray animal that has a long, flexible nose and two long tusks");
            dict.Add("emergency", "(noun) a serious, unexpected, and often dangerous situation requiring immediate action");
            dict.Add("encourage", "(verb) to inspire with courage, hope, or strength of mind");
            dict.Add("epic", "(adjective) heroic or grand in scale or character");
            dict.Add("equivalent", "(adjective) equal in value, force, meaning, or the like");
            dict.Add("erase", "(verb) rub out or remove");
            dict.Add("essence", "(noun) that which makes a thing to be what it is");
            dict.Add("eulogy", "(noun) a spoken or written laudation of a person's life or character");
            dict.Add("evening", "(noun) the part of the day between the end of the afternoon and night");
            dict.Add("evade", "(verb) to avoid by artifice");
            dict.Add("exceed", "(verb) to go beyond, as in measure, quality, value, action, power, skill, etc");
            dict.Add("fan", "(noun) an apparatus with rotating blades that creates a current of air for cooling or ventilation");
            dict.Add("fan", " someone who admires and supports a person, sport, sports team, etc.");
            dict.Add("father", "(noun) a male parent");
            dict.Add("fire", "(noun) material that is in the state of burning that produces flames that send out heat and light, and might produce smoke");
            dict.Add("fish", "(noun) a limbless cold-blooded vertebrate animal with gills and fins living wholly in water");
            dict.Add("flower", "(noun) the seed-bearing part of a plant, consisting of reproductive organs (stamens and carpels) that are typically surrounded by a brightly coloured corolla (petals) and a green calyx (sepals)");
            dict.Add("four", "(noun) the number 4");
            dict.Add("five", "(noun) the number 5");
            dict.Add("fox", "(noun) a carnivorous mammal of the dog family with a pointed muzzle and bushy tail, proverbial for its cunning");
            dict.Add("friend", "(noun) a person who you know well and who you like a lot, but who is usually not a member of your family");
            dict.Add("fun", "(noun) someone or something that is amusing or enjoyable : an enjoyable experience or person");
            dict.Add("fun", "\n\t(adjective) amusing or enjoyable");
            dict.Add("fun", "\n\t(verb) to speak or act in a way that is not serious");
            dict.Add("game", "(noun) an entertaining activity or sport, especially one played by children, or the equipment needed for such an activity");
            dict.Add("gentle", "(adjective) having or showing a kind and quiet nature");
            dict.Add("gentle", " not harsh or violent");
            dict.Add("girl", "(noun) a female child");
            dict.Add("glad", "(adjective) feeling pleasure, joy, or delight");
            dict.Add("go", "(verb) to move or travel to a place");
            dict.Add("good", "(adjective) of high quality");
            dict.Add("great", "(adjective) very large in amount or extent");
            dict.Add("guard", "(verb) to protect someone or something from danger or attack");
            dict.Add("hand", "(noun) the body part at the end of your arm that includes your fingers and thumb");
            dict.Add("happy", "(adjective) feeling pleasure and enjoyment because of your life, situation, etc");
            dict.Add("heart", "(noun) the organ in your chest that pumps blood through your veins and arteries");
            dict.Add("hello", "(noun) the act of saying the word hello to someone as a greeting");
            dict.Add("hit", "(verb) to cause or allow something, such as part of your body to touch something in a forceful or violent way");
            dict.Add("hole", "(noun) an opening into or through something");
            dict.Add("huge", "(adjective) very great in size, amount, or degree");
            dict.Add("hypothesis", "(noun) an idea or theory that is not proven but that leads to further study or discussion");
            dict.Add("ice", "(noun) water that has frozen and become solid, or pieces of this");
            dict.Add("ice-cream", "(noun) a very cold, sweet food made from frozen milk or cream, sugar, and a flavour");
            dict.Add("idea", "(noun) a suggestion or plan for doing something");
            dict.Add("if", "(conjunction) used to say that a particular thing can or will happen only after something else happens or becomes true");
            dict.Add("ignore", "(verb) to intentionally not listen or give attention to");
            dict.Add("ill", "(adjective) not feeling well, or suffering from a disease");
            dict.Add("image", "(noun) a picture in your mind or an idea of how someone or something is");
            dict.Add("in", "(prepostion) inside a container, place, or area, or surrounded or closed off by something");
            dict.Add("index", "(noun) a collection of information stored on a computer or on a set of cards, in alphabetical order");
            dict.Add("it", "(pronoun) used as the subject of a verb, or the object of a verb or preposition, to refer to a thing, animal, situation, or idea that has already been mentioned");
            dict.Add("jacket", "(noun) a short coat");
            dict.Add("jaw", "(noun) the lower part of your face that moves when you open your mouth");
            dict.Add("jam", "(noun) a sweet, soft food made by cooking fruit with sugar to preserve it. It is eaten on bread");
            dict.Add("jelly", "(noun) a sweet soft food made by cooking fruit with sugar to preserve it. It is smooth, without any pieces of fruit in it. Jelly is eaten on bread");
            dict.Add("jewelry", "(noun) decorative objects worn on your clothes or body that are usually made from valuable metals, such as gold and silver, and precious stones");
            dict.Add("jet", "(noun) an aircraft with a jet engine that is able to fly very fast");
            dict.Add("job", "(noun) the regular work that a person does to earn money");
            dict.Add("joke", "(noun) something, such as a funny story or trick, that is said or done in order to make people laugh");
            dict.Add("joy", "(noun) great happiness");
            dict.Add("join", "(verb) to connect or fasten things together");
            dict.Add("joint", "(adjective) belonging to or shared between two or more people");
            dict.Add("juice", "(noun) the liquid that comes from fruit or vegetables");
            dict.Add("judge", "(verb) to form, give, or have as an opinion, or to decide about something or someone, especially after thinking carefully");
            dict.Add("jump", "(verb) to push yourself suddenly off the ground and into the air using your legs");
            dict.Add("justice", "(noun) fairness in the way people are dealt with");
            dict.Add("keep", "(verb) to have or continue to have in your possession");
            dict.Add("key", "(noun) a piece of metal that has been cut into a special shape and is used for opening or closing a lock, starting a car engine, etc");
            dict.Add("kick", "(verb) to hit someone or something with the foot, or to move the feet and legs suddenly and violently");
            dict.Add("kid", "(noun) a child");
            dict.Add("kill", "(verb) to cause someone or something to die");
            dict.Add("kind", "(adjective) generous, helpful, and thinking about other people's feelings");
            dict.Add("king", "(noun) the title of a male ruler of a country, who holds this position because of his royal birth");
            dict.Add("kiss", "(verb) to touch with your lips, especially as a greeting, or to press your mouth onto another person's mouth in a sexual way");
            dict.Add("knee", "(noun) the middle joint of the leg that allows the leg to bend");
            dict.Add("knife", "(noun) a tool, usually with a metal blade and a handle, used for cutting and spreading food or other substances, or as a weapon");
            dict.Add("know", "(verb) to have information in your mind");
            dict.Add("knowledge", "(noun) understanding of or information about a subject that you get by experience or study, either known by one person or by people generally");
            dict.Add("knock", "(verb) to repeatedly hit something, producing a noise");
            dict.Add("lab", "(noun) a laboratory");
            dict.Add("lack", "(verb) to not have or not have enough of something that is needed or wanted");
            dict.Add("lady", "(noun) a polite or old-fashioned way of referring to or talking to a woman");
            dict.Add("land", "(noun) the surface of the earth that is not covered by water");
            dict.Add("last", "(adjective) the only one or part that is left");
            dict.Add("late", "(adjective) near the end of a period of time");
            dict.Add("laugh", "(verb) to smile while making sounds with your voice that show you think something is funny or you are happy");
            dict.Add("lazy", "(adjective) not willing to work or use any effort");
            dict.Add("learn", "(verb) to get knowledge or skill in a new subject or activity");
            dict.Add("lecture", "(noun) a formal talk on a serious subject given to a group of people, especially students");
            dict.Add("leave", "(verb) to go away from someone or something, for a short time or permanently");
            dict.Add("left", "(noun) a position that is the opposite of right and on the side of your body that contains the heart");
            dict.Add("leg", "(noun) one of the parts of the body of a human or animal that is used for standing or walking");
            dict.Add("level", "(noun) the height of something");
            dict.Add("let", "(verb) to allow something to happen or someone to do something by not doing anything to stop an action or by giving your permission");
            dict.Add("light", "(noun) the brightness that comes from the sun, fire, etc. and from electrical devices, and that allows things to be seen");
            dict.Add("lie", "(verb) to say or write something that is not true in order to deceive someone");
            dict.Add("lion", "(noun) a large wild animal of the cat family with yellowish-brown fur that lives in Africa and southern Asia");
            dict.Add("like", "(verb) to enjoy something");
            dict.Add("live", "(verb) to be alive");
            dict.Add("load", "(noun) something that is lifted and carried");
            dict.Add("love", "(noun)  a feeling of strong or constant affection for a person");
            dict.Add("love", "\n\t(verb) to feel great affection for someone");
            dict.Add("long", "(adjective) extending a great distance from one end to the other end : not short");
            dict.Add("lose", "(verb) to fail to win");
            dict.Add("lost", "(adjective) unable to be found");
            dict.Add("loss", "(noun) failure to keep or to continue to have something");
            dict.Add("look", "(verb) to direct your eyes in a particular direction");
            dict.Add("loud", "(adjective) making or causing a lot of noise");
            dict.Add("low", "(adjective) not rising or extending upward a great distance");
            dict.Add("luck", "(noun) the things that happen to a person because of chance");
            dict.Add("lucky", "(adjective) producing a good result by chance");
            dict.Add("lung", "(noun) either one of the two organs that people and animals use to breathe air");
            dict.Add("lunch", "(noun) a light meal eaten in the middle of the day");
            dict.Add("machine", "(noun) a piece of equipment with several moving parts that uses power to do a particular type of work");
            dict.Add("mail", "(noun) the letters, etc. that are sent to or from people, or the system for sending letters, etc. from place to place");
            dict.Add("man", "(noun) an adult male human being");
            dict.Add("male", "(noun) used to refer to men or boys, or the sex that fertilizes eggs, and does not produce babies or eggs itself");
            dict.Add("map", "(noun) a drawing that gives you a particular type of information about a particular area");
            dict.Add("many", "(adjective) a large number");
            dict.Add("make", "(verb) to produce something, often using a particular substance or material");
            dict.Add("mean", "(verb) to express or represent something such as an idea, thought, or fact");
            dict.Add("me", "(pronoun) used, usually as the object of a verb or preposition, to refer to the person speaking or writing");
            dict.Add("middle", "(noun) the central point, position, or part");
            dict.Add("minimum", "(noun) the smallest amount or number allowed or possible");
            dict.Add("minute", "(noun) one of the 60 parts that an hour is divided into, consisting of 60 seconds");
            dict.Add("miss", "(verb) to feel sad that a person or thing is not present");
            dict.Add("month", "(noun) a period of about four weeks, especially one of the twelve periods into which a year is divided");
            dict.Add("money", "(noun) coins or notes that are used to buy things, or an amount of these that a person has");
            dict.Add("more", "(adverb) a larger or extra number or amount");
            dict.Add("morning", "(noun) the part of the day from the time when the sun rises or you wake up until the middle of the day or lunch time");
            dict.Add("most", "(adjective) greatest in amount or degree");
            dict.Add("move", "(verb) to go from one place or position to another");
            dict.Add("mother", "(noun) a female parent");
            dict.Add("music", "(noun) sounds that are sung by voices or played on musical instruments");
            dict.Add("muscle", "(noun) one of many tissues in the body that can tighten and relax to produce movement");
            dict.Add("museum", "(noun) a building where objects of historical, scientific, or artistic interest are kept");
            dict.Add("my", "(adjective) relating to or belonging to me");
            dict.Add("mystery", "(noun) something that is not known");
            dict.Add("nail", "(noun) the hard covering at the end of a finger or toe");
            dict.Add("name", "(noun) a word or phrase that refers to or that can refer to a specific person");
            dict.Add("nature", "(noun) the natural forces that control what happens in the world");
            dict.Add("neck", "(noun) the part of the body between the head and the shoulders");
            dict.Add("need", "(verb) to be in a condition or situation in which you must have");
            dict.Add("negative", "(adjective) harmful or bad");
            dict.Add("nice", "(adjective) giving pleasure or joy");
            dict.Add("night", "(noun) the time of darkness between one day and the next");
            dict.Add("nine", "(noun) the number 9");
            dict.Add("no", "(adverb) used to give a negative answer or reply to a question");
            dict.Add("nobody", "(pronoun) no person");
            dict.Add("noon", "(noun) the middle of the day");
            dict.Add("none", "(pronoun) not any of a group of people or things");
            dict.Add("normal", "(adjective) usual or ordinary");
            dict.Add("now", "(adverb) at the present time");
            dict.Add("note", "(noun) information about a record, CD, or tape that is printed on its cover or on a piece of paper placed inside its cover");
            dict.Add("nurse", "(noun) a person who is trained to care for sick or injured people and who usually works in a hospital or doctor's office");
            dict.Add("obey", "(verb) to do what you are told or expected to do according to someone in authority or a rule or law");
            dict.Add("object", "(noun) a thing that you can see or touch but that is not usually a living animal, plant, or person");
            dict.Add("occur", "(verb) to happen");
            dict.Add("ocean", "(noun) a very large area of sea");
            dict.Add("October", "(noun) the tenth month of the year, after September and before November");
            dict.Add("odd", "(adjective) strange or unexpected");
            dict.Add("of", "(preposition) used to show possession, belonging, or origin");
            dict.Add("off", "(adverb) away from a place or position, especially the present place, position, or time");
            dict.Add("office", "(noun) a room or part of a building in which people work");
            dict.Add("often", "(adverb) many times");
            dict.Add("oil", "(noun) a thick liquid that comes from petroleum, used as a fuel and for making parts of machines move easily");
            dict.Add("okay", "(adjective) agreed or acceptable");
            dict.Add("old", "(adjective) having lived or existed for many years");
            dict.Add("on", "(prepositon) used to show that something is in a position above something else and touching it, or that something is moving into such a position");
            dict.Add("one", "(noun) the number 1");
            dict.Add("once", "(adverb) one single time");
            dict.Add("only", "(adjective) used to show that there is a single one or very few of something, or that there are no others");
            dict.Add("open", "(adjective) not closed or fastened");
            dict.Add("orange", "(noun) a round sweet fruit that has a thick orange skin and an orange centre divided into many parts");
            dict.Add("orange", " a colour between red and yellow");
            dict.Add("original", "(adjective) existing since the beginning, or being the earliest form of something");
            dict.Add("other", "(pronoun) the second of two things or people, or the thing or person that is left in a group or set of things");
            dict.Add("our", "(pronoun) of or belonging to us");
            dict.Add("out", "(preposition) used to show movement away from the inside of a place or container");
            dict.Add("over", "(preposition) above or higher than something else, sometimes so that one thing covers the other");
            dict.Add("palm", "(noun) the inside part of your hand from your wrist to the base of your fingers");
            dict.Add("paper", "(noun) thin, flat material made from crushed wood or cloth, used for writing, printing, or drawing on");
            dict.Add("parent", "(noun) a mother or father of a person or an animal");
            dict.Add("park", "(verb) to put a vehicle in a place where it can stay for a period of time, usually while you leave it");
            dict.Add("part", "(noun) some but not all of a thing");
            dict.Add("pass", "(verb) to go past a particular point in time");
            dict.Add("past", "(adverb) in or to a position that is further than a particular point");
            dict.Add("path", "(noun) a route or track between one place and another, or the direction in which something is moving");
            dict.Add("pay", "(verb) to give money to someone for something you want to buy or for services provided");
            dict.Add("pen", "(noun) a long, thin object used for writing or drawing with ink");
            dict.Add("perfect", "(adjective) complete and correct in every way, of the best possible type or without fault");
            dict.Add("phone", "(noun) a device that uses either a system of wires along which electrical signals are sent");
            dict.Add("physical", "(adjective) relating to the body");
            dict.Add("photo", "(noun) a photograph");
            dict.Add("pick", "(verb) to take some things and leave others");
            dict.Add("pig", "(noun) a large pink, brown, or black farm animal with short legs and a curved tail, kept for its meat");
            dict.Add("play", "(verb) to take part in a game or other organized activity");
            dict.Add("player", "(noun) someone who takes part in a game or sport");
            dict.Add("point", "(noun) a mark or unit for counting, especially how much a person or team has scored in a sport");
            dict.Add("poison", "(noun) a substance that can make people or animals ill or kill them if they eat or drink it");
            dict.Add("police", "(noun) an official force whose job is to maintain public order, deal with crime, and make people obey the law, or the members of this force");
            dict.Add("poor", "(adjective) having little money and/or few possessions");
            dict.Add("pool", "(noun) a small area of usually still water");
            dict.Add("potato", "(noun) a round vegetable that grows underground and has white flesh with light brown, red, or pink skin, or the plant on which these grow");
            dict.Add("pray", "(verb) to hope for something very much");
            dict.Add("prepare", "(verb) to make or get something or someone ready for something that will happen in the future");
            dict.Add("pretty", "(adjective) pleasant to look at");
            dict.Add("pro", "(noun) someone who has a lot of experience or skill in a particular job or activity");
            dict.Add("psycho", "(noun) someone who is crazy and frightening");
            dict.Add("pupil", "(noun) a child or young person who is being taught");
            dict.Add("qualification", "(noun) a special skill or type of experience or knowledge that makes someone suitable to do a particular job or activity");
            dict.Add("qualify", "(verb) to give someone the necessary skill or knowledge to do a particular job or activity");
            dict.Add("quality", "(noun) how good or bad something is");
            dict.Add("quantity", "(noun) an amount or number of something");
            dict.Add("queen", "(noun) a woman who rules a country and who usually inherits her position and rules for life");
            dict.Add("question", "(noun) a sentence, phrase, or word that asks for information or is used to test someone's knowledge");
            dict.Add("quick", "(adjective) done or happening in a short amount of time");
            dict.Add("quit", "(verb) to stop doing");
            dict.Add("quiz", "(noun) a short spoken or written test that is often taken without preparation");
            dict.Add("quote", "(verb) to write or say the exact words of someone");
            dict.Add("race", "(noun) competition");
            dict.Add("rage", "(noun) anger");
            dict.Add("radio", "(noun) a piece of electronic equipment used for listening to radio broadcasts");
            dict.Add("rain", "(noun) drops of water from clouds");
            dict.Add("rank", "(noun) position");
            dict.Add("reach", "(verb) arrive");
            dict.Add("react", "(verb) to act in a particular way as a direct result of something else");
            dict.Add("real", "(adjective) existing in fact and not imaginary");
            dict.Add("ready", "(adjective) prepared");
            dict.Add("really", "(adverb) not imaginary");
            dict.Add("reason", "(noun) explanation");
            dict.Add("reality", "(noun) the state of things as they are, rather than as they are imagined to be");
            dict.Add("red", "(adjective) of the colour of fresh blood");
            dict.Add("rich", "(adjective) having a lot of money or valuable possessions");
            dict.Add("rice", "(noun) the small seeds of a particular type of grass, cooked, and eaten as food");
            dict.Add("rhythm", "(noun) a strong pattern of sounds, words, or musical notes that is used in music, poetry, and dancing");
            dict.Add("ride", "(verb) to sit on something such as a bicycle, motorbike, or horse and travel along on it controlling its movements");
            dict.Add("role", "(noun) duty");
            dict.Add("room", "(noun) a part of the inside of a building that is separated from other parts by walls, floor, and ceiling");
            dict.Add("rock", "(noun) a stone");
            dict.Add("rob", "(verb) to take money or property illegally from a place, organization, or person, often using violence");
            dict.Add("run", "(verb) to move with your legs at a speed that is faster than walking");
            dict.Add("rude", "(adjective) not polite");
            dict.Add("rule", "(noun) a statement that tells you what is or is not allowed in a particular game, situation, etc");
            dict.Add("sad", "(adjective) unhappy or sorry");
            dict.Add("sale", "(noun) an act of exchanging something for money");
            dict.Add("say", "(verb) speak");
            dict.Add("same", "(adjective) exactly like");
            dict.Add("save", "(verb) to keep something");
            dict.Add("safe", "(adjective) not in danger");
            dict.Add("scare", "(verb) to feel frightened");
            dict.Add("scene", "(noun) a part of a play or film in which the action stays in one place for a continuous period of time");
            dict.Add("school", "(noun) a place where children go to be educated");
            dict.Add("score", "(verb) to win or get a point, goal, etc. in a competition, sport, game, or test");
            dict.Add("screen", "(noun) a flat surface in a cinema, on a television, or as part of a computer, on which pictures or words are shown");
            dict.Add("scream", "(verb) to make noise");
            dict.Add("sea", "(noun) a large area of salt water");
            dict.Add("search", "(verb) to look somewhere carefully in order to find something");
            dict.Add("second", " immediately after the first and before any others");
            dict.Add("see", "(verb) to be conscious of what is around you by using your eyes");
            dict.Add("sell", "(verb) to give something to someone else in return for money");
            dict.Add("shadow", "(noun) an area of darkness, caused by light being blocked by something");
            dict.Add("ship", "(noun) a large boat for travelling on water, especially across the sea");
            dict.Add("sheep", "(noun) a farm animal with thick wool that eats grass and is kept for its wool, skin, and meat");
            dict.Add("shoe", "(noun) one of a pair of coverings for your feet");
            dict.Add("shirt", "(noun) a piece of clothing worn");
            dict.Add("shoot", "(verb) to fire a bullet or an arrow");
            dict.Add("short", "(adjective) small in length, distance, or height");
            dict.Add("shop", "(noun) a place where you can buy goods or services");
            dict.Add("shy", "(adjective) nervous and uncomfortable with other people");
            dict.Add("sick", "(adjective) physically or mentally ill");
            dict.Add("show", "(verb) to make it possible for something to be seen");
            dict.Add("sister", "(noun) a girl or woman who has the same parents as another person");
            dict.Add("sign", "(noun) a notice giving information, directions, a warning, etc");
            dict.Add("silent", "(adjective) without any sound");
            dict.Add("sing", "(verb) to make musical sounds with the voice, usually a tune with words");
            dict.Add("singer", "(noun) a person who sings");
            dict.Add("six", "(noun) the number 6");
            dict.Add("seven", "(noun) the number 7");
            dict.Add("skill", "(noun) an ability to do an activity or job well, especially because you have practised it");
            dict.Add("skin", "(noun) the natural outer layer that covers a person, animal, fruit, etc");
            dict.Add("sky", "(noun) the area above the earth, in which clouds, the sun, etc. can be seen");
            dict.Add("sleep", "(noun) the resting state in which the body is not active and the mind is unconscious");
            dict.Add("sit", "(verb) to be in a position in which the lower part of the body is resting on a seat or other type of support, with the upper part of the body vertical");
            dict.Add("single", "(adjective) one only");
            dict.Add("small", "(adjective) little in size or amount when compared with what is typical or average");
            dict.Add("smile", "(verb) to make a happy or friendly expression in which the corners of your mouth curve up");
            dict.Add("smoke", "(noun) grey gas");
            dict.Add("snow", "(noun) the small, soft, white pieces of ice that sometimes fall from the sky when it is cold");
            dict.Add("sneeze", "(verb) to send air out from the nose and mouth in an explosive way that you cannot control");
            dict.Add("so", "(adverb) very, extremely, or to such a degree");
            dict.Add("soccer", "(noun) a game played between two teams of eleven people, where each team tries to win by kicking a ball into the other team's goal");
            dict.Add("social", "(adjective) relating to activities in which you meet and spend time with other people and that happen during the time when you are not working");
            dict.Add("software", "(noun) the instructions that control what a computer does; computer programs");
            dict.Add("some", "an amount or number of something that is not stated or not known; a part of something");
            dict.Add("somebody", "(pronoun) someone");
            dict.Add("son", "(noun) your male child");
            dict.Add("soon", "(adverb) quickly");
            dict.Add("sometime", "(adverb) at a time in the future or the past that is not known or not stated");
            dict.Add("something", "(pronoun) an object, situation, quality, or action that is not exactly known or stated");
            dict.Add("space", "(noun) an empty area that is available to be used");
            dict.Add("sound", "(noun) something that you can hear or that can be heard");
            dict.Add("source", "(noun) the place something comes from or starts at, or the cause of something");
            dict.Add("sorry", "(adjective) feeling sadness, sympathy, or disappointment, especially because something unpleasant has happened or been done");
            dict.Add("sort", "(verb) to put a number of things in an order or to separate them into groups");
            dict.Add("speak", "(verb) to say words");
            dict.Add("spend", "(verb) to give money as a payment for something");
            dict.Add("spicy", "(adjective) containing strong flavours from spices");
            dict.Add("start", "(verb) to begin doing something");
            dict.Add("stay", "(verb) to not move away from or leave a place or situation");
            dict.Add("star", "(noun) a very large ball of burning gas in space that is usually seen from the earth as a point of light in the sky at night");
            dict.Add("stand", "(verb) to be in a vertical state");
            dict.Add("step", "(verb) to move by lifting your foot and putting it down in a different place, or to put your foot on or in something");
            dict.Add("still", "(adverb) continuing");
            dict.Add("stop", "(verb) finish");
            dict.Add("study", "(verb) learn");
            dict.Add("student", "(noun) a person who is learning at a college or university");
            dict.Add("strong", "(adjective) powerful, not weak");
            dict.Add("stress", "(noun) worry");
            dict.Add("such", "(adjective) so great");
            dict.Add("success", "(noun) the achieving of the results wanted or hoped for");
            dict.Add("sugar", "(noun) a sweet substance");
            dict.Add("sun", "(noun) the star that provides light and heat for the earth and around which the earth moves");
            dict.Add("sunny", "(adjective) having plenty of bright sunlight");
            dict.Add("sympathy", "(noun) the feeling that you care about and are sorry about someone else's trouble, grief, misfortune, etc");
            dict.Add("take", "(verb) to carry or move something to a place");
            dict.Add("ten", "(noun) the number 10");
            dict.Add("team", "(noun) a group of people who compete in a sport, game, etc., against another group");
            dict.Add("teach", "(verb) to cause or help someone to learn about a subject by giving lessons");
            dict.Add("teacher", "(noun) a person or thing that teaches something");
            dict.Add("technical", "(adjective) relating to the practical use of machines or science in industry, medicine, etc");
            dict.Add("technology", "(noun) the use of science in industry, engineering, etc., to invent useful things or to solve problems");
            dict.Add("thank", "(verb) to tell someone that you are grateful for something that he or she has done or given");
            dict.Add("think", "(verb) to have an opinion about someone or something");
            dict.Add("tie", "(verb)  to attach someone or something to something with a string, rope, etc");
            dict.Add("time", "(noun) the thing that is measured as seconds, minutes, hours, days, years, etc");
            dict.Add("tonight", "(noun) this night or the night following this day");
            dict.Add("tomorrow", "(noun) the day after today");
            dict.Add("today", "(noun) this day");
            dict.Add("train", "(verb) to prepare someone or yourself for a job, activity, or sport, by learning skills and/or by mental or physical exercise");
            dict.Add("trip", "(noun) a journey to a place");
            dict.Add("tuition", "(noun) money that is paid to a school for the right to study there");
            dict.Add("two", "(noun) the number 2");
            dict.Add("three", "(noun) the number 3");
            dict.Add("ugly", "(verb) unpleasant to look at : not pretty or attractive");
            dict.Add("uncle", "(noun) the brother of your father or mother or the husband of your aunt");
            dict.Add("under", "(adverb) in or to a lower place than something");
            dict.Add("understand", "(verb) to know the meaning of something");
            dict.Add("up", "(adverb) from a lower to a higher place or position");
            dict.Add("use", "(verb) to do something with in order to accomplish a task, do an activity, etc");
            dict.Add("useful", "(adjective) helping to do or achieve something");
            dict.Add("usually", "(adverb) used to describe what happens or exists most of the time or in most cases");
            dict.Add("vacation", "(noun) a period of time that a person spends away from home, school, or business usually in order to relax or travel");
            dict.Add("value", "(noun) the amount of money that something is worth");
            dict.Add("view", "(noun) an opinion or way of thinking about something");
            dict.Add("virus", "(noun) an extremely small particle that causes a disease and that spreads from one person or animal to another");
            dict.Add("visit", "(verb) to go somewhere to spend time with someone");
            dict.Add("vote", "(verb) to make a decision about by voting");
            dict.Add("voice", "(noun) the sounds that you make with your mouth and throat when you are speaking, singing, etc");
            dict.Add("visitor", "(noun) someone who visits a person or place");
            dict.Add("wait", "(verb) to allow time to go by");
            dict.Add("waiter", "(noun) a man whose job is to bring the food to customers at their tables in a restaurant");
            dict.Add("wake", "(verb) to cause someone to become awake and conscious after sleeping");
            dict.Add("walk", "(verb) to move along by putting one foot in front of the other, allowing each foot to touch the ground before lifting the next");
            dict.Add("work", "(noun) an activity, such as a job, that a person uses physical or mental effort to do, usually for money");
            dict.Add("want", "(verb) to wish for a particular thing or plan of action");
            dict.Add("water", "(noun) a clear liquid, without colour or taste, that falls from the sky as rain and is necessary for animal and plant life");
            dict.Add("weak", "(adjective) not physically strong");
            dict.Add("we", "(pronoun) used as the subject of a verb to refer to a group including the speaker and at least one other person");
            dict.Add("week", "(noun) a period of seven days, especially either from Monday to Sunday or from Sunday to Saturday");
            dict.Add("weekend", "(noun) Saturday and Sunday, or Friday evening until Sunday night");
            dict.Add("welcome", "(verb) to be pleased about and encourage or support something");
            dict.Add("well", "(adverb) in a good way, to a high or satisfactory standard");
            dict.Add("web", "(noun) the system of connected documents on the internet");
            dict.Add("what", "(pronoun) used to ask for information about someone or something");
            dict.Add("who", "(pronoun) what or which person or people");
            dict.Add("where", "(adverb) to, at, or in what place");
            dict.Add("white", "(adjective) of a colour like that of snow, milk, or bone");
            dict.Add("when", "(adverb) at what time, at the time at which");
            dict.Add("which", "(pronoun) used as the subject or object of a verb to show what thing or things you are referring to");
            dict.Add("win", "(verb) to achieve first position and/or get a prize in a competition, election, fight, etc");
            dict.Add("will", "(modal verb) used to talk about what is going to happen in the future");
            dict.Add("wife", "(noun) the woman that you are married to");
            dict.Add("why", "(adverb) for what reason");
            dict.Add("with", "(preposition) used to say that people or things are in a place together or are doing something together");
            dict.Add("world", "(noun) the earth and all the people, places, and things on it");
            dict.Add("word", "(noun) a sound or combination of sounds that has a meaning and is spoken or written");
            dict.Add("woman", "(noun) an adult female human being");
            dict.Add("wrong", "(adjective) not agreeing with the facts or truth");
            dict.Add("X-ray", "(noun) a type of radiation that can go through many solid substances, allowing hidden objects such as bones and organs in the body to be photographed");
            dict.Add("year", "(noun) a unit of time that is equal to 12 months or 365 or sometimes 366 days");
            dict.Add("yesterday", "(noun) the day before today");
            dict.Add("young", "(adjective)  in an early stage of life, growth, or development");
            dict.Add("your", "(adjective) relating to or belonging to you");
            dict.Add("youth", "(noun) the time of life when someone is young");
            dict.Add("you", "(pronoun) used to refer to the person or group of people that is being addressed as the subject of a verb or as the object of a verb or preposition");
            dict.Add("yet", "(adverb) until now");
            dict.Add("yes", "(adverb) used to give a positive answer or reply to a question, request, or offer");
            dict.Add("yellow", "(adjective) having the color of the sun or of ripe lemons");
            dict.Add("yawn", "(verb) to open your mouth wide while taking in breath usually because you are tired or bored");
            dict.Add("zero", "(noun) the number 0");
            dict.Add("zone", "(noun) an area that is different from other areas in a particular way");
            dict.Add("zoo", "(noun) a place where many kinds of animals are kept so that people can see them");

            int op;
            
            do
            {
                
                Clear();
                Write("==================================\n" +
                "1/ Search a word\n" +
                "2/ Add word & translation the word\n" +
                "3/ Delete a word from the dictionary\n" +
                "0/ Exit\n" +
                "==================================\n" +
                "Enter options [1-3] : ");
                op = int.Parse(ReadLine());
                switch (op)
                {
                    case 1:
                        {
                            Clear();
                            Write("Input a word : ");
                            string search = ReadLine();
                            foreach (string k in dict.AllKeys)
                            {
                                if (k == search)
                                {
                                    WriteLine(search + " : " + dict[search]);
                                }
                            }
                            ReadKey();
                        }
                        break;
                    case 2:
                        {
                            Clear();
                            Write("Input a word : ");
                            string vocab = ReadLine();
                            Write("Input difinition : ");
                            string difinition = ReadLine();
                            dict.Add(vocab, difinition);
                        }
                        break;
                    case 3:
                        {
                            Clear();
                            Write("Input a word for delete: ");
                            string del = ReadLine();
                            dict.Remove(del);
                        }
                        break;
                    default:
                        {
                            Clear();
                            if (op != 0 ) WriteLine("Wrong option!");
                            else if (op == 0) WriteLine("Thanks for using this program!");
                        }
                        break;
                }
            } while (op != 0);
        }
        
    }
}
